name: Compile the Klimerko sketch, and generate the binary

on:
  pull_request:
    paths:
      - ".github/workflows/klimerko-compile.yml"
      - "Klimerko_Firmware/**"
  push:
    paths:
      - ".github/workflows/klimerko-compile.yml"
      - "Klimerko_Firmware/**"
  workflow_dispatch:
  repository_dispatch:

env:
  SKETCHES_REPORTS_PATH: sketches-reports
  SKETCHES_REPORTS_ARTIFACT_NAME: Klimerko
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fqbn: 
          - "esp8266:esp8266:nodemcuv2"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Compile sketch
        uses: arduino/compile-sketches@v1.1.2
        with:
            fqbn: ${{ matrix.fqbn }} 
            platforms: |
              - name: esp8266:esp8266
                source-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
                version: 3.1.2
                # version: default
            libraries: |
              - 
            sketch-paths: |
              - ./Klimerko_Firmware/
            sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

            cli-compile-flags: |
              - -e
              - --output-dir
              - ./
              
      - name: Save binary file
        run: |
          mkdir -p ${{ github.workspace }}/binaries
          ls .
          ls ..
          ls -R ../..
          cp ./*.bin ${{ github.workspace }}/binaries/Klimerko.bin

      - name: Get latest version tag
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Commit and push binary
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add binaries/Klimerko.bin
          git commit -m "Add auto-compiled binary"
          git push
    
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }} 
          body: "Automated release of Klimerko binary"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    
      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }} 
          files: binaries/Klimerko.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  

#      - name: Upload sketches report to workflow artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}
#          path: ${{ env.SKETCHES_REPORTS_PATH }}
