name: Compile the Klimerko sketch, and generate the binary

on:
  pull_request:
    paths:
      - ".github/workflows/klimerko-compile.yml"
      - "Klimerko_Firmware/**"
  push:
    paths:
      - ".github/workflows/klimerko-compile.yml"
      - "Klimerko_Firmware/**"
  workflow_dispatch:
  repository_dispatch:

env:
  SKETCHES_REPORTS_PATH: sketches-reports
  SKETCHES_REPORTS_ARTIFACT_NAME: Cookie-Cats

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fqbn: 
          - "esp8266:esp8266:nodemcuv2"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Compile sketch
        uses: arduino/compile-sketches@v1.1.2
        with:
            fqbn: ${{ matrix.fqbn }} 
            platforms: |
              - name: esp8266:esp8266
                source-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
                version: 3.1.2
                # version: default
            libraries: |
              - ./Klimerko_Firmware/src/* 
            sketch-paths: |
              - ./Klimerko_Firmware/
